rango/urls.py
from django.conf.urls import url
from rango import views

from rango.views import AboutView

# app_name = 'rango'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^about/', AboutView.as_view(), name='about'),
	url(r'^add_category/$', views.add_category, name='add_category'),

	url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),

	url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.show_category, name='show_category'),

	# url(r'^register/$', views.register, name='register'),
	# url(r'^login/$', views.user_login, name='login'),
	# url(r'^logout/$', views.user_logout, name='logout'),

	url(r'^restricted/', views.restricted, name="restricted"),

	# url(r'^search/$', views.search, name="search"),
	url(r'^goto/', views.track_url, name="goto"),
	url(r'^register_profile/', views.register_profile, name="register_profile"),
	url(r'^profile/(?P<username>[\w\-]+)/$', views.profile, name="profile"),
	url(r'^profiles/$', views.list_profiles, name="list_profiles")
]

tango_with_django_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static
from rango.views import MyRegistrationView

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^rango/', include('rango.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^admin/', admin.site.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models

from django.template.defaultfilters import slugify

from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
	name = models.CharField(max_length=128, unique=True)
	views = models.IntegerField(default=0)
	likes = models.IntegerField(default=0)
	slug = models.SlugField(unique=True)

	def save(self, *args, **kwargs):
		self.slug = slugify(self.name)
		super(Category, self).save(*args, **kwargs)

	class Meta:
		verbose_name_plural = "Categories"
		
	def __str__(self):
		return self.name


class Page(models.Model):
	category = models.ForeignKey(Category)
	title = models.CharField(max_length=128)
	url = models.URLField()
	views = models.IntegerField(default=0)

	def __str__(self):
		return self.title


class UserProfile(models.Model):
	# Required line, links UserProfile to a User model instance
	user = models.OneToOneField(User)

	# Additional attributes
	website = models.URLField(blank=True)
	picture = models.ImageField(upload_to='profile_images', blank=True)

	# Override to return something meaningful
	def __str__(self):
		return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Page, Category, UserProfile

max_length_char_field = 128


class CategoryForm(forms.ModelForm):
	name = forms.CharField(max_length=max_length_char_field, help_text="Please enter the category name.")
	views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
	likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
	slug = forms.CharField(widget=forms.HiddenInput(), required=False)

	# An inline class to provide additional information on the form
	class Meta:
		# provide association between ModelFrom and a model
		model = Category
		fields = ('name',)


class PageForm(forms.ModelForm):
	title = forms.CharField(max_length=max_length_char_field, help_text="Please enter the title of the page.")
	url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
	views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

	class Meta:
		# Provide an association between the ModelForm and a model
		model = Page

		# What fields do we want to include in our form?
		# This way we don't need every field in the model present
		# Some fields may allow NULL values so we may not want to include them
		# Here we are hiding the foreign key
		# we can either exclude the category field from the form
		exclude = ('category',)
		# or specify the fields to include (i.e. dont include the category field)
		# fields = ('title', 'url', 'views')


class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta:
		model = User
		fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
	website = forms.URLField(required=False)
	picture = forms.ImageField(required=False)

	class Meta:
		model = UserProfile
		exclude = ('user',)

rango/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse

# from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Import the Category and Page model
from rango.models import Category, Page, User, UserProfile
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm

from datetime import datetime
from rango.webhose_search import run_query
from django.core.exceptions import ObjectDoesNotExist
from registration.backends.simple.views import RegistrationView

from django.views.generic import View


def index(request):
	# request.session.set_test_cookie()
	# Retrieve top 5 most viewed pages
	page_list = Page.objects.order_by('-views')[:5]

	# Query the database for a list of ALL categories currently stored
	# Order the categories by no. of likes in descending order 100 99 98 etc.
	# Retrieve the top 5 only - or all if less than 5
	# Place the list in our context_dict dictionary
	# that will be passed to the template engine

	category_list = Category.objects.order_by('-likes')[:5]

	context_dict = {
		'categories': category_list,
		'pages': page_list
	}

	# Call the helper function to handle the cookies
	visitor_cookie_handler(request)
	context_dict['visits'] = request.session['visits']

	# Obtain our response object
	response = render(request, 'rango/index.html', context_dict)

	# Return response back to the user, updating any cookies that need changed
	return response


class AboutView(View):
	def get(self, request):
		visitor_cookie_handler(request)
		context_dict = {
			'visits': request.session['visits']
		}
		return render(request, 'rango/about.html', context_dict)


"""def about(request):
	# if request.session.test_cookie_worked():
	# print("TEST COOKIE WORKED")
	# request.session.delete_test_cookie()

	visitor_cookie_handler(request)
	context_dict = {
		'visits': request.session['visits']
	}

	return render(request, 'rango/about.html', context_dict)"""


def show_category(request, category_name_slug):
	# Create a context dictionary which we can pass to the template rendering engine.
	context_dict = {}

	try:
		# Can we find a category name slug with the given name?
		# If we can't, the .get() method raises a DoesNotExist exception
		# So the .get() method returns one model instance or raises an exception
		category = Category.objects.get(slug=category_name_slug)

		# Retrieve all of the associated pages
		# Note that filter() will return a list of pages or an empty list
		pages = Page.objects.filter(category=category).order_by('-views')

		# Adds our results list to the template context under name pages
		context_dict["pages"] = pages

		# We also add the category object from the database to the context dictionary
		# We'll use this in the template to verify that the category exists
		context_dict['category'] = category
	except Category.DoesNotExist:
		# We get here if we didn't find the specified category, don't do anything
		# the template will display the "no category" message for us
		context_dict['category'] = None
		context_dict['pages'] = None

		# If category doesn't exist, return early
		return render(request, 'rango/category.html', context_dict)

	# Set query to be the default category name
	context_dict['query'] = category.name
	result_list = []

	# Use Webhose to get results (from online)
	if request.method == 'POST':
		query = request.POST['query'].strip()
		if query:
			result_list = run_query(query)
			context_dict['query'] = query

	context_dict['result_list'] = result_list

	# Go render the response and return it to the client
	return render(request, 'rango/category.html', context_dict)


@login_required()
def add_category(request):
	form = CategoryForm()

	# Was the Http request a post?
	if request.method == 'POST':
		form = CategoryForm(request.POST)

		# Have we been provided with a valid form?
		if form.is_valid():
			# Save the new category to the database
			form.save(commit=True)
			# Now that the category is saved
			# We could give a confirmation message
			# But since the most recent category added is on the index page
			# Then we can direct the user back to the index page
			return index(request)
		else:
			# The supplied form contained errors
			# just print them to the terminal
			print(form.errors)

	# Will handle the bad form, new form, or no form supplied cases
	# Render the form with error messages (if any).
	return render(request, 'rango/add_category.html', {'form': form})


@login_required()
def add_page(request, category_name_slug):
	try:
		category = Category.objects.get(slug=category_name_slug)
	except Category.DoesNotExist:
		category = None

	form = PageForm()

	# Was the Http request a post?
	if request.method == 'POST':
		form = PageForm(request.POST)

		# Have we been provided with a valid form?
		if form.is_valid():
			if category:
				page = form.save(commit=False)
				page.category = category
				page.views = 0
				page.save()
				return show_category(request, category_name_slug)
		else:
			# The supplied form contained errors
			# just print them to the terminal
			print(form.errors)

	context_dict = {'form': form, "category": category}
	return render(request, 'rango/add_page.html', context_dict)


"""
def register(request):
	# tells template whether the registration was successful
	registered = False

	if request.method == 'POST':
		# attempt to grab info from raw form
		user_form = UserForm(data=request.POST)
		profile_form = UserProfileForm(data=request.POST)

		if user_form.is_valid() and profile_form.is_valid():
			# Save user form data
			user = user_form.save()

			# hash password with set_password method, once hashed, save it
			user.set_password(user.password)
			user.save()

			# now let's sort out UserProfile instance, need to set user attributes ourselves
			# so set commit=False, it will delay saving the model until we're ready
			# avoids integrity problems

			profile = profile_form.save(commit=False)
			profile.user = user

			# if they provided a pic, get it from input form and put it into UserProfile model
			if 'picture' in request.FILES:
				profile.picture = request.FILES['picture']

			# save model instance
			profile.save()

			registered = True
		else:
			print(user_form.errors, profile_form.errors)
	else:
		# not a HTTP POST request, render again (Blank)
		user_form = UserForm()
		profile_form = UserProfileForm()

	return render(request, 'rango/register.html', {
		'user_form': user_form,
		'profile_form': profile_form,
		'registered': registered
	})


def user_login(request):
	if request.method == 'POST':
		# Gather user and pass provided by user, info obtained from login form
		# We use request.POST.get() as it will return none if the value does not
		# exist whereas request.POST[] will raise a KeyError exception
		username = request.POST.get('username')
		password = request.POST.get('password')

		# use django to see if user/pass combo is valid, a User object is returned if so
		user = authenticate(username=username, password=password)

		if user:
			# if account is active (it may have been disabled)
			if user.is_active:
				# valid and active => login then send back to homepage
				login(request, user)
				return HttpResponseRedirect(reverse('index'))
			else:
				return HttpResponse("Your Rango account is disabled.")
		else:
			# bad login details provided
			print("Invalid login details: {0}, {1}".format(username, password))
			return render(request, 'rango/login.html', {
				'invalid_details': True
			})

	else:
		# Request is not HTTP POST so display login form
		# no context variables to pass to template
		return render(request, 'rango/login.html', {})


# Only those who are logged in can log out
@login_required()
def user_logout(request):
	# since we know they are logged in
	logout(request)
	return HttpResponseRedirect(reverse('index'))
"""


class MyRegistrationView(RegistrationView):
	def get_success_url(self, user=None):
		return reverse('register_profile')


@login_required
def restricted(request):
	return render(request, 'rango/restricted.html', {})


# A helper method
def get_server_side_cookie(request, cookie, default_val=None):
	val = request.session.get(cookie)
	if not val:
		val = default_val
	return val


# A Helper method
def visitor_cookie_handler(request):

	visits = int(get_server_side_cookie(request, 'visits', '1'))

	last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))

	# Creates datetime object of the specified format
	last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

	# If it's been more than a day since the last visit
	if (datetime.now() - last_visit_time).days > 1:
		visits = visits + 1
		# Update the last visit cookie now that we have updated the count
		request.session['last_visit'] = str(datetime.now())
	else:
		# Set the last visit cookie
		request.session['last_visit'] = last_visit_cookie

	# Update/set the visits cookie
	request.session['visits'] = visits


def search(request):
	result_list = []
	context_dict = {}

	if request.method == 'POST':
		query = request.POST['query'].strip()
		if query:
			result_list = run_query(query)
			context_dict['user_query'] = query

	context_dict['result_list'] = result_list

	return render(request, 'rango/search.html', context_dict)


def track_url(request):
	page_id = None
	url = '/rango/'

	if request.method == 'GET':
		# Get request received
		if 'page_id' in request.GET:
			page_id = request.GET['page_id']
			# Page ID found

	if page_id:
		try:
			# get page object with page id, increment view and save
			page = Page.objects.get(pk=page_id)
			page.views += 1
			page.save()

			# redirect user to the page url
			url = page.url

		except ObjectDoesNotExist:
			# Page ID was invalid, i.e. couldn't find page object
			# return HttpResponse("Page id {0} not found".format(page_id))
			pass

templates/rango/about.html
<!DOCTYPE html>

{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title %}
    About
{% endblock %}

{% block body_block %}
    Rango says here is the about page. <br />
    This tutorial has been put together by Mohammad Majid. <br />
    Visits: {{ visits }}<br />

    <button class="btn btn-primary" onClick="alert('You clicked the button using JavaScript.');">
        Click Me - I run JavaScript
    </button>

    <button class="btn btn-primary" id="about-btn">
        Click Me - I'm JavaScript on Speed
    </button>
    <p>This is a example</p>
    <p>This is another example</p>

    <div id="msg">Hello - I'm here for a JQuery Example too</div>

    <br />
    <div>
        <img src="{{ MEDIA_URL }}cat.jpg" alt="Cat" />
        <img src="{% static "images/rango2.jpg" %}" alt="Picture of Rango2" />
    </div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %}Create a Category{% endblock %}

{% block body_block %}
    <form id="category_form" method="post" action="{% url 'add_category' %}">
        <h2 class="form-signin-heading">Create a Category</h2>
        {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
        <br/>
        {{form.non_field_errors}}
        <button class="btn btn-primary" type="submit" name="submit">Create Category</button>
        </form>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title %}
    Add a Page to {{ category.name }}
{% endblock %}

{% block body_block %}
    {% if category %}

        <form role="form" id="page_form" method="post" action="{% url 'add_page' category.slug %}">
            <h2 class="form-signin-heading">Add a Page to <a href="{% url 'show_category' category.slug %}">{{ category.name }}</a></h2>
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
        <br/>
        {{form.non_field_errors}}
        <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
        </form>
    {% else %}
        <p>This category does not exist.</p>
    {% endif %}
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
        Rango - {% block title %}How to Tango with Django!{% endblock %}
    </title>
    <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
        <button class="navbar-toggler navbar-toggler-right hidden-lg-up"
                type="button"
                data-toggle="collapse" data-target="#navbar"
                aria-controls="navbar"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>

        <a class="navbar-brand" href="{% url 'index' %} ">Rango</a>


        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav mr-auto">

                <button class="btn btn-dark" id="menu-toggle">Toggle Sidebar</button>&nbsp;

                {% if request.resolver_match.view_name == 'index' %}
                    <li class="nav-item active">{% else %}
                    <li class="nav-item">
                {% endif %}
                <a class="nav-link" href="{% url 'index' %}">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about' %}">About</a>
                </li>

                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'restricted' %}">Restrictedgit </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'add_category' %}">Create a New Category</a>
                    </li>
                {% endif %}
            </ul>


            <ul class="navbar-nav ml-auto">

                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'list_profiles' %}">List Profiles</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile' user.username %}">My Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth_password_change' %}">Change Password</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a>
                    </li>
                {% else %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'registration_register' %}">Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth_login' %}">Log In</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}../admin/">Admin</a>
                </li>

            </ul>
        </div>
    </nav>

    <div class="d-flex" id="wrapper">
        <!-- Sidebar -->
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="sidebar-heading">Categories</div>
            <div class="list-group list-group-flush">
                {% block sidebar_block %}
                    {% get_category_list category %}
                {% endblock %}
            </div>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">


            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>


            <div class="container-fluid">
                {% block body_block %}{% endblock %}
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- Bootstrap core JavaScript ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>

    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/rango-jquery.js" %}"></script>

    <!-- Menu Toggle Script -->
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
    </script>

</body>
</html>

templates/rango/category.html
<!DOCTYPE html>

{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title %}{% if category %} {{ category.name }} {% else %} Error {% endif %}{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>



        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li>
                        <a href="{% url 'goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
                        ({{ page.views }} view{{ page.views|pluralize }})
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}
        {% if user.is_authenticated %}
            <a href="{% url 'add_page' category.slug %}">Add a Page</a>
        {% endif %}

        <hr>
        {% if user.is_authenticated %}
            <div>
                <h4>Can't find a page you're looking for? Search here!</h4>
                <br/>
                <form class="form-inline" id="user_form"
                      method="post" action="{% url 'show_category' category.slug %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <input class="form-control" type="text" size="50"
                               name="query" value="{{ query }}" id="query"/>
                    </div>
                    <button class="btn btn-primary" type="submit" name="submit"
                            value="Search">Search
                    </button>
                </form>

                <br/>

                <div>
                    {% if result_list %}
                        <h3>Results</h3>
                        <!-- Display results in an ordered list -->
                        <div class="list-group">
                            {% for result in result_list %}
                                <div class="list-group-item">
                                    <h4 class="list-group-item-heading">
                                        <a href="{{ result.link }}">{{ result.title }}</a>
                                    </h4>
                                    <p class="list-group-item-text">{{ result.summary }}</p>
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
        {% endif %}

    {% else %}
        The specified category does not exist!
    {% endif %}
{% endblock %}

templates/rango/cats.html
{% if cats %}
    {% for c in cats %}
        {% if c == act_cat %}
            <a href="{% url 'show_category' c.slug %}"
               class="list-group-item list-group-item-action bg-light"><strong>{{ c.name }}</strong></a>

        {% else %}
            <a href="{% url 'show_category' c.slug %}"
               class="list-group-item list-group-item-action bg-light">{{ c.name }}</a>
        {% endif %}
    {% endfor %}
{% else %}
    <li><strong>There are no categories present.</strong></li>
{% endif %}

templates/rango/index.html
<!DOCTYPE html>

{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title %}Home{% endblock %}

{% block body_block %}
    <div class="jumbotron">
        <h1 class="display-3">Rango says...</h1>
        {% if user.is_authenticated %}
            <h1>hey there {{ user.username }} </h1>
        {% else %}
            <h1>hey there partner!</h1>
        {% endif %}
    </div>

    <div>
        Visits: {{ visits }}
    </div>

    <div class="row marketing">
        <div class="col-lg-6">
            <h4>Most Liked Categories</h4>
            {% if categories %}
                <ul class="list-group">
                    {% for category in categories %}
                        <li class="list-group-item">
                            <a href="{% url 'show_category' category.slug %}">{{ category.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <strong>There are no categories present.</strong>
            {% endif %}
        </div>


        <div class="col-lg-6">
            <h4>Most Viewed Pages</h4>
            {% if pages %}
                <ul class="list-group">
                    {% for page in pages %}
                        <li class="list-group-item">
                            <a href="{{ page.url }}">{{ page.title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <strong>There are no pages present.</strong>
            {% endif %}
        </div>
    </div>

    <br/>
    <div>
        <img class="img-fluid" src="{% static "images/rango.jpg" %}" alt="Picture of Rango"/>
    </div>
{% endblock %}

templates/rango/list_profiles.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title %}User Profiles{% endblock %}

{% block body_block %}

    <h1>User Profiles</h1>
    <div class="panel">
        {% if userprofile_list %}
        <div class="panel-heading">
            <div class="panel-body">
                <div class="list-group">
                    {% for listuser in userprofile_list %}
                    <div class="list-group-item">
                        <h4 class="list-group-item-heading">
                            {% if listuser.picture %}
                                <img src="{{ MEDIA_URL }}{{ listuser.picture }}"
                                         width="50" height="50"
                                     alt="{{ listuser.user.username }}"/>
                            {% else %}
                                <img src="http://lorempixel.com/50/50/nature/"
                                     width="50" height="50"
                                     alt="{{ listuser.user.username }}"/>
                            {% endif %}
                            <a href="{% url 'profile' listuser.user.username %}">
                                &nbsp;&nbsp;{{ listuser.user.username }}
                            </a>
                        </h4>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% else %}
            <p>
                There are no users for the site.
            </p>
        {% endif %}
    </div>


{% endblock %}

templates/rango/profile.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title %}
    Profile - {{ selecteduser.username }}
{% endblock %}

{% block body_block %}

    <h1>{{ selecteduser.username }}</h1>
    <img src="{{ MEDIA_URL }}{{ userprofile.picture }}"
         width="300" height="300" alt="{{ selecteduser.username }}"/>
    <br/>
    <div>
        {% if selecteduser.username == user.username %}
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Update" />
            </form>
        {% else %}
            <p><strong>Website: </strong><a href="{{ userprofile.website }}">
                {{ userprofile.website }}</a></p>
        {% endif %}
    </div>
    <div id="edit_profile"></div>
{% endblock %}

templates/rango/profile_registration.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title %}
    Sign Up - Step 2
{% endblock %}

{% block body_block %}

    <form role="form" id="page_form" method="post" action="{% url 'register_profile' %}"
          enctype="multipart/form-data">

        <h2 class="form-signin-heading">Sign Up - Step 2</h2>
        {% csrf_token %}
        {{ form.as_p }}

        <!--<label for="id_website" class="sr-only">Website</label>
        <input type="url" name="website" id="id_website" class="form-control" placeholder="Website URL"/>
        {# form.website.errors }}
         form.website.help_text }} #}

        <label for="id_picture" class="sr-only">Select a profile image</label>
        <input type="file" name="picture" id="id_picture"/>
        {#   form.picture.errors }}
         form.picture.help_text }}

         form.non_field_errors #}-->

        <button class="btn btn-primary" type="submit" name="submit">Sign Up</button>
    </form>
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title %}Restricted{% endblock %}

{% block body_block %}
    Since you're logged in, you can see this text!
{% endblock %}